
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore-cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # - run:
      #     name: install MeCab
      #     command: |
      #       sudo apt-get update;
      #       sudo apt-get -y install mecab libmecab-dev mecab-ipadic-utf8
      - run:
          name: install package pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
            pytest -vv --disable-warnings --cov=src --cov-report=html:test-reports
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - store_artifacts:
          path: test-reports/
          destination: circleci-docs
